"""Add email to supplier

Revision ID: 3b19c8c6bdbd
Revises: ce47c95994b1
Create Date: 2021-08-15 21:18:25.078178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b19c8c6bdbd'
down_revision = 'ce47c95994b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suppliers', sa.Column('email', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suppliers', 'email')
    # ### end Alembic commands ###
