"""Add default to Product

Revision ID: a1e441fa06c1
Revises: a451e7bf6c97
Create Date: 2021-08-07 17:08:27.804006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1e441fa06c1'
down_revision = 'a451e7bf6c97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'unit_quoted_price',
               existing_type=sa.REAL(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'unit_quoted_price',
               existing_type=sa.REAL(),
               nullable=True)
    # ### end Alembic commands ###
