"""Update Orders table

Revision ID: ce47c95994b1
Revises: a1e441fa06c1
Create Date: 2021-08-11 17:05:46.408722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce47c95994b1'
down_revision = 'a1e441fa06c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('community_id', sa.String(length=128), nullable=True))
    op.add_column('orders', sa.Column('payment_method', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'payment_method')
    op.drop_column('orders', 'community_id')
    # ### end Alembic commands ###
